# we have to running as caddy2 user, assume user is already created by
# caddy2 role
- name: create siot group
  group:
    name: "{{ siot_user }}"
  when: siot_user != "caddy2"

- name: create siot user
  user:
    name: "{{ siot_user }}"
    group: "{{ siot_user }}"
    home: "{{ siot_data_dir }}"
  when: siot_user != "caddy2"

- name: Create directories
  file: path={{ item }} state=directory owner={{ siot_user }} mode='0770'
  with_items:
    - "{{ siot_data_dir }}"

- name: fetch siot binary
  get_url:
    url: "{{ siot_download }}"
    dest: "{{ siot_data_dir }}/siot.tar.gz"
  register: fetch

- name: extract siot
  unarchive:
    src: "{{ siot_data_dir }}/siot.tar.gz"
    dest: "{{ siot_data_dir }}"
    copy: no
    owner: "{{ siot_user }}"
    group: "{{ siot_user }}"
  when: fetch.changed
  register: extract
  notify: restart siot

- name: install siot binary
  copy:
    remote_src: yes
    src: "{{ siot_data_dir}}/simpleiot-v{{ siot_version }}-linux-x86_64/siot"
    dest: /usr/local/bin/{{ siot_binary }}
    mode: "0755"
    owner: "{{ siot_user }}"
  when: extract.changed
  notify:
    - restart siot
    - enable siot

- name: install service file
  template:
    src=siot.service.j2 dest=/etc/systemd/system/{{ siot_binary }}.service
  notify:
    - reload systemd
    - restart siot
    - enable siot
